disabled_rules:
- line_length
- identifier_name
- empty_parentheses_with_trailing_closure

excluded:
- Pods
- tellingMe/appDelegate/AppDelegate.siwft
- tellingMe/appDelegate/SceneDelegate.swift
included:

