disabled_rules:
- line_length
- identifier_name
- empty_parentheses_with_trailing_closure
- redundant_optional_initialization
- cyclomatic_complexity

excluded:
- Pods
- tellingMe/app/AppDelegate.siwft
- tellingMe/app/SceneDelegate.swift
included:

