# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'
post_install do |installer|
    installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
               end
          end
   end
end

target 'tellingMe' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Gifu'
  pod 'SwiftLint'
  pod 'KakaoSDKCommon'
  pod 'KakaoSDKAuth'
  pod 'KakaoSDKUser'
  pod 'Moya'
  pod 'GradientProgress'
  pod 'KeychainSwift'
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Messaging'
  # Pods for tellingMe

end
